# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../tips/ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1228, 823)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(-1, 2, -1, 2)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.selectFileButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectFileButton.sizePolicy().hasHeightForWidth())
        self.selectFileButton.setSizePolicy(sizePolicy)
        self.selectFileButton.setObjectName("selectFileButton")
        self.horizontalLayout_4.addWidget(self.selectFileButton)
        self.filenameLE = QtWidgets.QLineEdit(self.centralwidget)
        self.filenameLE.setReadOnly(True)
        self.filenameLE.setObjectName("filenameLE")
        self.horizontalLayout_4.addWidget(self.filenameLE)
        self.clearcacheBtn = QtWidgets.QPushButton(self.centralwidget)
        self.clearcacheBtn.setObjectName("clearcacheBtn")
        self.horizontalLayout_4.addWidget(self.clearcacheBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.weigLogo = QtWidgets.QLabel(self.tab)
        self.weigLogo.setMaximumSize(QtCore.QSize(200, 200))
        self.weigLogo.setObjectName("weigLogo")
        self.horizontalLayout_32.addWidget(self.weigLogo)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.hopdistanceLE = QtWidgets.QLineEdit(self.tab)
        self.hopdistanceLE.setMaximumSize(QtCore.QSize(60, 16777215))
        self.hopdistanceLE.setReadOnly(True)
        self.hopdistanceLE.setObjectName("hopdistanceLE")
        self.gridLayout.addWidget(self.hopdistanceLE, 3, 1, 1, 1)
        self.ywidthLE = QtWidgets.QLineEdit(self.tab)
        self.ywidthLE.setMaximumSize(QtCore.QSize(60, 16777215))
        self.ywidthLE.setReadOnly(True)
        self.ywidthLE.setObjectName("ywidthLE")
        self.gridLayout.addWidget(self.ywidthLE, 2, 1, 1, 1)
        self.xwidthLE = QtWidgets.QLineEdit(self.tab)
        self.xwidthLE.setMaximumSize(QtCore.QSize(60, 16777215))
        self.xwidthLE.setReadOnly(True)
        self.xwidthLE.setObjectName("xwidthLE")
        self.gridLayout.addWidget(self.xwidthLE, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.acqtimeLE = QtWidgets.QLineEdit(self.tab)
        self.acqtimeLE.setMaximumSize(QtCore.QSize(60, 16777215))
        self.acqtimeLE.setMaxLength(10)
        self.acqtimeLE.setObjectName("acqtimeLE")
        self.gridLayout.addWidget(self.acqtimeLE, 2, 3, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 2, 1, 1)
        self.nchannelsLE = QtWidgets.QLineEdit(self.tab)
        self.nchannelsLE.setMaximumSize(QtCore.QSize(60, 16777215))
        self.nchannelsLE.setReadOnly(True)
        self.nchannelsLE.setObjectName("nchannelsLE")
        self.gridLayout.addWidget(self.nchannelsLE, 3, 3, 1, 1)
        self.cyclesLE = QtWidgets.QLineEdit(self.tab)
        self.cyclesLE.setMaximumSize(QtCore.QSize(60, 16777215))
        self.cyclesLE.setReadOnly(True)
        self.cyclesLE.setObjectName("cyclesLE")
        self.gridLayout.addWidget(self.cyclesLE, 1, 3, 1, 1)
        self.horizontalLayout_32.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.labviewprogramCBox = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labviewprogramCBox.sizePolicy().hasHeightForWidth())
        self.labviewprogramCBox.setSizePolicy(sizePolicy)
        self.labviewprogramCBox.setMinimumSize(QtCore.QSize(250, 0))
        self.labviewprogramCBox.setObjectName("labviewprogramCBox")
        self.labviewprogramCBox.addItem("")
        self.labviewprogramCBox.setItemText(0, "")
        self.labviewprogramCBox.addItem("")
        self.labviewprogramCBox.addItem("")
        self.labviewprogramCBox.addItem("")
        self.labviewprogramCBox.addItem("")
        self.labviewprogramCBox.addItem("")
        self.labviewprogramCBox.addItem("")
        self.labviewprogramCBox.addItem("")
        self.labviewprogramCBox.addItem("")
        self.labviewprogramCBox.addItem("")
        self.labviewprogramCBox.addItem("")
        self.labviewprogramCBox.addItem("")
        self.labviewprogramCBox.addItem("")
        self.labviewprogramCBox.addItem("")
        self.labviewprogramCBox.addItem("")
        self.labviewprogramCBox.addItem("")
        self.verticalLayout_4.addWidget(self.labviewprogramCBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_32.addLayout(self.verticalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem2)
        self.verticalFrame_4 = QtWidgets.QFrame(self.tab)
        self.verticalFrame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.verticalFrame_4.setObjectName("verticalFrame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalFrame_4)
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plotAllDataBtn = QtWidgets.QPushButton(self.verticalFrame_4)
        self.plotAllDataBtn.setObjectName("plotAllDataBtn")
        self.verticalLayout_2.addWidget(self.plotAllDataBtn)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.xchannelCBox = QtWidgets.QCheckBox(self.verticalFrame_4)
        self.xchannelCBox.setObjectName("xchannelCBox")
        self.horizontalLayout_37.addWidget(self.xchannelCBox)
        self.ychannelCBox = QtWidgets.QCheckBox(self.verticalFrame_4)
        self.ychannelCBox.setObjectName("ychannelCBox")
        self.horizontalLayout_37.addWidget(self.ychannelCBox)
        self.zchannelCBox = QtWidgets.QCheckBox(self.verticalFrame_4)
        self.zchannelCBox.setObjectName("zchannelCBox")
        self.horizontalLayout_37.addWidget(self.zchannelCBox)
        self.lnchannelCBox = QtWidgets.QCheckBox(self.verticalFrame_4)
        self.lnchannelCBox.setObjectName("lnchannelCBox")
        self.horizontalLayout_37.addWidget(self.lnchannelCBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.c1channelCBox = QtWidgets.QCheckBox(self.verticalFrame_4)
        self.c1channelCBox.setEnabled(True)
        self.c1channelCBox.setCheckable(True)
        self.c1channelCBox.setChecked(False)
        self.c1channelCBox.setObjectName("c1channelCBox")
        self.horizontalLayout_41.addWidget(self.c1channelCBox)
        self.v1channelCBox = QtWidgets.QCheckBox(self.verticalFrame_4)
        self.v1channelCBox.setObjectName("v1channelCBox")
        self.horizontalLayout_41.addWidget(self.v1channelCBox)
        self.c2channelCBox = QtWidgets.QCheckBox(self.verticalFrame_4)
        self.c2channelCBox.setObjectName("c2channelCBox")
        self.horizontalLayout_41.addWidget(self.c2channelCBox)
        self.v2channelCBox = QtWidgets.QCheckBox(self.verticalFrame_4)
        self.v2channelCBox.setObjectName("v2channelCBox")
        self.horizontalLayout_41.addWidget(self.v2channelCBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_32.addWidget(self.verticalFrame_4)
        self.verticalLayout_31.addLayout(self.horizontalLayout_32)
        self.infoLayout_2 = QtWidgets.QFrame(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoLayout_2.sizePolicy().hasHeightForWidth())
        self.infoLayout_2.setSizePolicy(sizePolicy)
        self.infoLayout_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.infoLayout_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.infoLayout_2.setObjectName("infoLayout_2")
        self.infoLayout = QtWidgets.QHBoxLayout(self.infoLayout_2)
        self.infoLayout.setContentsMargins(5, 2, 5, 5)
        self.infoLayout.setSpacing(5)
        self.infoLayout.setObjectName("infoLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.infoLayout_2)
        self.label_8.setMinimumSize(QtCore.QSize(0, 16))
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.localSettingsTE = QtWidgets.QTextEdit(self.infoLayout_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localSettingsTE.sizePolicy().hasHeightForWidth())
        self.localSettingsTE.setSizePolicy(sizePolicy)
        self.localSettingsTE.setObjectName("localSettingsTE")
        self.verticalLayout_5.addWidget(self.localSettingsTE)
        self.infoLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.infoLayout_2)
        self.label_9.setMinimumSize(QtCore.QSize(0, 16))
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.globalSettingsTE = QtWidgets.QTextEdit(self.infoLayout_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.globalSettingsTE.sizePolicy().hasHeightForWidth())
        self.globalSettingsTE.setSizePolicy(sizePolicy)
        self.globalSettingsTE.setObjectName("globalSettingsTE")
        self.verticalLayout_6.addWidget(self.globalSettingsTE)
        self.infoLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.infoLayout_2)
        self.label_10.setMinimumSize(QtCore.QSize(0, 16))
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.channelsTE = QtWidgets.QTextEdit(self.infoLayout_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channelsTE.sizePolicy().hasHeightForWidth())
        self.channelsTE.setSizePolicy(sizePolicy)
        self.channelsTE.setObjectName("channelsTE")
        self.verticalLayout_7.addWidget(self.channelsTE)
        self.infoLayout.addLayout(self.verticalLayout_7)
        self.frame_4 = QtWidgets.QFrame(self.infoLayout_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_8.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_8.setSpacing(1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_25 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_8.addWidget(self.label_25)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ZCN_LE = QtWidgets.QLineEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZCN_LE.sizePolicy().hasHeightForWidth())
        self.ZCN_LE.setSizePolicy(sizePolicy)
        self.ZCN_LE.setMaximumSize(QtCore.QSize(30, 16777215))
        self.ZCN_LE.setMaxLength(2)
        self.ZCN_LE.setObjectName("ZCN_LE")
        self.gridLayout_2.addWidget(self.ZCN_LE, 2, 1, 1, 1)
        self.YCN_LE = QtWidgets.QLineEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.YCN_LE.sizePolicy().hasHeightForWidth())
        self.YCN_LE.setSizePolicy(sizePolicy)
        self.YCN_LE.setMaximumSize(QtCore.QSize(30, 16777215))
        self.YCN_LE.setText("")
        self.YCN_LE.setMaxLength(2)
        self.YCN_LE.setObjectName("YCN_LE")
        self.gridLayout_2.addWidget(self.YCN_LE, 1, 1, 1, 1)
        self.V2CN_LE = QtWidgets.QLineEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.V2CN_LE.sizePolicy().hasHeightForWidth())
        self.V2CN_LE.setSizePolicy(sizePolicy)
        self.V2CN_LE.setMaximumSize(QtCore.QSize(30, 16777215))
        self.V2CN_LE.setObjectName("V2CN_LE")
        self.gridLayout_2.addWidget(self.V2CN_LE, 3, 3, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.frame_4)
        self.label_30.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 2, 2, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.frame_4)
        self.label_44.setObjectName("label_44")
        self.gridLayout_2.addWidget(self.label_44, 1, 2, 1, 1)
        self.C1CN_LE = QtWidgets.QLineEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C1CN_LE.sizePolicy().hasHeightForWidth())
        self.C1CN_LE.setSizePolicy(sizePolicy)
        self.C1CN_LE.setMaximumSize(QtCore.QSize(30, 16777215))
        self.C1CN_LE.setMaxLength(2)
        self.C1CN_LE.setObjectName("C1CN_LE")
        self.gridLayout_2.addWidget(self.C1CN_LE, 0, 3, 1, 1)
        self.LNCN_LE = QtWidgets.QLineEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LNCN_LE.sizePolicy().hasHeightForWidth())
        self.LNCN_LE.setSizePolicy(sizePolicy)
        self.LNCN_LE.setMaximumSize(QtCore.QSize(30, 16777215))
        self.LNCN_LE.setMaxLength(2)
        self.LNCN_LE.setObjectName("LNCN_LE")
        self.gridLayout_2.addWidget(self.LNCN_LE, 3, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.frame_4)
        self.label_26.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 2, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.frame_4)
        self.label_27.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 1, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.frame_4)
        self.label_45.setObjectName("label_45")
        self.gridLayout_2.addWidget(self.label_45, 3, 2, 1, 1)
        self.V1CN_LE = QtWidgets.QLineEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.V1CN_LE.sizePolicy().hasHeightForWidth())
        self.V1CN_LE.setSizePolicy(sizePolicy)
        self.V1CN_LE.setMaximumSize(QtCore.QSize(30, 16777215))
        self.V1CN_LE.setMaxLength(2)
        self.V1CN_LE.setObjectName("V1CN_LE")
        self.gridLayout_2.addWidget(self.V1CN_LE, 2, 3, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame_4)
        self.label_28.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 0, 0, 1, 1)
        self.C2CN_LE = QtWidgets.QLineEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C2CN_LE.sizePolicy().hasHeightForWidth())
        self.C2CN_LE.setSizePolicy(sizePolicy)
        self.C2CN_LE.setMaximumSize(QtCore.QSize(30, 16777215))
        self.C2CN_LE.setObjectName("C2CN_LE")
        self.gridLayout_2.addWidget(self.C2CN_LE, 1, 3, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.frame_4)
        self.label_29.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 3, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.frame_4)
        self.label_31.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_31.setObjectName("label_31")
        self.gridLayout_2.addWidget(self.label_31, 0, 2, 1, 1)
        self.XCN_LE = QtWidgets.QLineEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XCN_LE.sizePolicy().hasHeightForWidth())
        self.XCN_LE.setSizePolicy(sizePolicy)
        self.XCN_LE.setMaximumSize(QtCore.QSize(30, 16777215))
        self.XCN_LE.setText("")
        self.XCN_LE.setMaxLength(2)
        self.XCN_LE.setObjectName("XCN_LE")
        self.gridLayout_2.addWidget(self.XCN_LE, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.frame_4)
        self.label_24.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 4, 0, 1, 1)
        self.DTCN_LE = QtWidgets.QLineEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DTCN_LE.sizePolicy().hasHeightForWidth())
        self.DTCN_LE.setSizePolicy(sizePolicy)
        self.DTCN_LE.setMaximumSize(QtCore.QSize(30, 16777215))
        self.DTCN_LE.setObjectName("DTCN_LE")
        self.gridLayout_2.addWidget(self.DTCN_LE, 4, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_2)
        self.setCNBtn = QtWidgets.QPushButton(self.frame_4)
        self.setCNBtn.setEnabled(False)
        self.setCNBtn.setObjectName("setCNBtn")
        self.verticalLayout_8.addWidget(self.setCNBtn)
        self.infoLayout.addWidget(self.frame_4)
        self.verticalLayout_31.addWidget(self.infoLayout_2)
        self.tabWidget.addTab(self.tab, "")
        self.plotmapsTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.plotmapsTab.sizePolicy().hasHeightForWidth())
        self.plotmapsTab.setSizePolicy(sizePolicy)
        self.plotmapsTab.setObjectName("plotmapsTab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.plotmapsTab)
        self.verticalLayout_10.setContentsMargins(12, 2, 12, 2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label = QtWidgets.QLabel(self.plotmapsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setLineWidth(1)
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        self.plotTopoBtn = QtWidgets.QPushButton(self.plotmapsTab)
        self.plotTopoBtn.setObjectName("plotTopoBtn")
        self.horizontalLayout_9.addWidget(self.plotTopoBtn)
        self.flattenTopoChBox = QtWidgets.QCheckBox(self.plotmapsTab)
        self.flattenTopoChBox.setObjectName("flattenTopoChBox")
        self.horizontalLayout_9.addWidget(self.flattenTopoChBox)
        self.topo3DChBox = QtWidgets.QCheckBox(self.plotmapsTab)
        self.topo3DChBox.setObjectName("topo3DChBox")
        self.horizontalLayout_9.addWidget(self.topo3DChBox)
        self.normalizeTopoChBox = QtWidgets.QCheckBox(self.plotmapsTab)
        self.normalizeTopoChBox.setChecked(True)
        self.normalizeTopoChBox.setObjectName("normalizeTopoChBox")
        self.horizontalLayout_9.addWidget(self.normalizeTopoChBox)
        self.checkBox_10 = QtWidgets.QCheckBox(self.plotmapsTab)
        self.checkBox_10.setObjectName("checkBox_10")
        self.horizontalLayout_9.addWidget(self.checkBox_10)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.line_7 = QtWidgets.QFrame(self.plotmapsTab)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_9.addWidget(self.line_7)
        self.label_19 = QtWidgets.QLabel(self.plotmapsTab)
        self.label_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_9.addWidget(self.label_19)
        self.replaceNaNsChBox = QtWidgets.QCheckBox(self.plotmapsTab)
        self.replaceNaNsChBox.setChecked(False)
        self.replaceNaNsChBox.setObjectName("replaceNaNsChBox")
        self.horizontalLayout_9.addWidget(self.replaceNaNsChBox)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_20 = QtWidgets.QLabel(self.plotmapsTab)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_17.addWidget(self.label_20)
        self.nanthresholdLE = QtWidgets.QLineEdit(self.plotmapsTab)
        self.nanthresholdLE.setObjectName("nanthresholdLE")
        self.verticalLayout_17.addWidget(self.nanthresholdLE)
        self.horizontalLayout_9.addLayout(self.verticalLayout_17)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.plotCurrentDensityChBox = QtWidgets.QCheckBox(self.plotmapsTab)
        self.plotCurrentDensityChBox.setObjectName("plotCurrentDensityChBox")
        self.verticalLayout_19.addWidget(self.plotCurrentDensityChBox)
        self.horizontalLayout_9.addLayout(self.verticalLayout_19)
        self.smoothDataMapChBox = QtWidgets.QCheckBox(self.plotmapsTab)
        self.smoothDataMapChBox.setObjectName("smoothDataMapChBox")
        self.horizontalLayout_9.addWidget(self.smoothDataMapChBox)
        self.smoothDataMapSpBox = QtWidgets.QSpinBox(self.plotmapsTab)
        self.smoothDataMapSpBox.setMinimum(3)
        self.smoothDataMapSpBox.setMaximum(900)
        self.smoothDataMapSpBox.setSingleStep(2)
        self.smoothDataMapSpBox.setObjectName("smoothDataMapSpBox")
        self.horizontalLayout_9.addWidget(self.smoothDataMapSpBox)
        self.verticalLayout_10.addLayout(self.horizontalLayout_9)
        self.line_2 = QtWidgets.QFrame(self.plotmapsTab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_10.addWidget(self.line_2)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.plotmapsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.iEmovieChBox = QtWidgets.QCheckBox(self.plotmapsTab)
        self.iEmovieChBox.setChecked(True)
        self.iEmovieChBox.setObjectName("iEmovieChBox")
        self.horizontalLayout_8.addWidget(self.iEmovieChBox)
        self.itmovieChBox = QtWidgets.QCheckBox(self.plotmapsTab)
        self.itmovieChBox.setObjectName("itmovieChBox")
        self.horizontalLayout_8.addWidget(self.itmovieChBox)
        self.EtmovieChBox = QtWidgets.QCheckBox(self.plotmapsTab)
        self.EtmovieChBox.setObjectName("EtmovieChBox")
        self.horizontalLayout_8.addWidget(self.EtmovieChBox)
        self.label_14 = QtWidgets.QLabel(self.plotmapsTab)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_8.addWidget(self.label_14)
        self.multicyclemovieSpin = QtWidgets.QSpinBox(self.plotmapsTab)
        self.multicyclemovieSpin.setMinimum(1)
        self.multicyclemovieSpin.setObjectName("multicyclemovieSpin")
        self.horizontalLayout_8.addWidget(self.multicyclemovieSpin)
        self.cmapMovieCbox = QtWidgets.QComboBox(self.plotmapsTab)
        self.cmapMovieCbox.setObjectName("cmapMovieCbox")
        self.cmapMovieCbox.addItem("")
        self.cmapMovieCbox.addItem("")
        self.horizontalLayout_8.addWidget(self.cmapMovieCbox)
        self.plotMoviesBtn = QtWidgets.QPushButton(self.plotmapsTab)
        self.plotMoviesBtn.setObjectName("plotMoviesBtn")
        self.horizontalLayout_8.addWidget(self.plotMoviesBtn)
        self.stopMovieBtn = QtWidgets.QPushButton(self.plotmapsTab)
        self.stopMovieBtn.setObjectName("stopMovieBtn")
        self.horizontalLayout_8.addWidget(self.stopMovieBtn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.line_5 = QtWidgets.QFrame(self.plotmapsTab)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_8.addWidget(self.line_5)
        self.plotSingleFrameBtn = QtWidgets.QPushButton(self.plotmapsTab)
        self.plotSingleFrameBtn.setObjectName("plotSingleFrameBtn")
        self.horizontalLayout_8.addWidget(self.plotSingleFrameBtn)
        self.frameNumRBtn = QtWidgets.QRadioButton(self.plotmapsTab)
        self.frameNumRBtn.setChecked(True)
        self.frameNumRBtn.setObjectName("frameNumRBtn")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.frameNumRBtn)
        self.horizontalLayout_8.addWidget(self.frameNumRBtn)
        self.singleframeSB = QtWidgets.QSpinBox(self.plotmapsTab)
        self.singleframeSB.setMinimum(1)
        self.singleframeSB.setMaximum(3000000)
        self.singleframeSB.setObjectName("singleframeSB")
        self.horizontalLayout_8.addWidget(self.singleframeSB)
        self.frameXvalueRBtn = QtWidgets.QRadioButton(self.plotmapsTab)
        self.frameXvalueRBtn.setChecked(False)
        self.frameXvalueRBtn.setObjectName("frameXvalueRBtn")
        self.buttonGroup.addButton(self.frameXvalueRBtn)
        self.horizontalLayout_8.addWidget(self.frameXvalueRBtn)
        self.frameXvalueLE = QtWidgets.QLineEdit(self.plotmapsTab)
        self.frameXvalueLE.setObjectName("frameXvalueLE")
        self.horizontalLayout_8.addWidget(self.frameXvalueLE)
        self.showFrameListBtn = QtWidgets.QPushButton(self.plotmapsTab)
        self.showFrameListBtn.setObjectName("showFrameListBtn")
        self.horizontalLayout_8.addWidget(self.showFrameListBtn)
        self.line_6 = QtWidgets.QFrame(self.plotmapsTab)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_8.addWidget(self.line_6)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout_11.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(8)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_15 = QtWidgets.QLabel(self.plotmapsTab)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_11.addWidget(self.label_15)
        self.label_13 = QtWidgets.QLabel(self.plotmapsTab)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self.videospeedSB = QtWidgets.QSpinBox(self.plotmapsTab)
        self.videospeedSB.setMinimum(1)
        self.videospeedSB.setMaximum(5000)
        self.videospeedSB.setProperty("value", 50)
        self.videospeedSB.setObjectName("videospeedSB")
        self.horizontalLayout_11.addWidget(self.videospeedSB)
        self.skipframesChBox = QtWidgets.QCheckBox(self.plotmapsTab)
        self.skipframesChBox.setObjectName("skipframesChBox")
        self.horizontalLayout_11.addWidget(self.skipframesChBox)
        self.skipframesSB = QtWidgets.QSpinBox(self.plotmapsTab)
        self.skipframesSB.setMinimum(1)
        self.skipframesSB.setMaximum(500)
        self.skipframesSB.setObjectName("skipframesSB")
        self.horizontalLayout_11.addWidget(self.skipframesSB)
        self.saveMovieChBox = QtWidgets.QCheckBox(self.plotmapsTab)
        self.saveMovieChBox.setObjectName("saveMovieChBox")
        self.horizontalLayout_11.addWidget(self.saveMovieChBox)
        self.movieNoGUIChBox = QtWidgets.QCheckBox(self.plotmapsTab)
        self.movieNoGUIChBox.setEnabled(False)
        self.movieNoGUIChBox.setObjectName("movieNoGUIChBox")
        self.horizontalLayout_11.addWidget(self.movieNoGUIChBox)
        self.label_47 = QtWidgets.QLabel(self.plotmapsTab)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_11.addWidget(self.label_47)
        self.autoLimitsRBtn = QtWidgets.QRadioButton(self.plotmapsTab)
        self.autoLimitsRBtn.setChecked(True)
        self.autoLimitsRBtn.setObjectName("autoLimitsRBtn")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.autoLimitsRBtn)
        self.horizontalLayout_11.addWidget(self.autoLimitsRBtn)
        self.dynamicLimitsRBtn = QtWidgets.QRadioButton(self.plotmapsTab)
        self.dynamicLimitsRBtn.setObjectName("dynamicLimitsRBtn")
        self.buttonGroup_2.addButton(self.dynamicLimitsRBtn)
        self.horizontalLayout_11.addWidget(self.dynamicLimitsRBtn)
        self.manualLimitsRBtn = QtWidgets.QRadioButton(self.plotmapsTab)
        self.manualLimitsRBtn.setChecked(False)
        self.manualLimitsRBtn.setObjectName("manualLimitsRBtn")
        self.buttonGroup_2.addButton(self.manualLimitsRBtn)
        self.horizontalLayout_11.addWidget(self.manualLimitsRBtn)
        self.label_32 = QtWidgets.QLabel(self.plotmapsTab)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_11.addWidget(self.label_32)
        self.movieMinLimitLE = QtWidgets.QLineEdit(self.plotmapsTab)
        self.movieMinLimitLE.setObjectName("movieMinLimitLE")
        self.horizontalLayout_11.addWidget(self.movieMinLimitLE)
        self.label_33 = QtWidgets.QLabel(self.plotmapsTab)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_11.addWidget(self.label_33)
        self.movieMaxLimitLE = QtWidgets.QLineEdit(self.plotmapsTab)
        self.movieMaxLimitLE.setObjectName("movieMaxLimitLE")
        self.horizontalLayout_11.addWidget(self.movieMaxLimitLE)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        self.verticalLayout_10.addLayout(self.verticalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.plotmapsTab)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.iEAnalysisTab = QtWidgets.QWidget()
        self.iEAnalysisTab.setObjectName("iEAnalysisTab")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.iEAnalysisTab)
        self.horizontalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.plotSinglePeakMapsBtn = QtWidgets.QPushButton(self.iEAnalysisTab)
        self.plotSinglePeakMapsBtn.setObjectName("plotSinglePeakMapsBtn")
        self.horizontalLayout_14.addWidget(self.plotSinglePeakMapsBtn)
        self.plotp2p1Btn = QtWidgets.QPushButton(self.iEAnalysisTab)
        self.plotp2p1Btn.setObjectName("plotp2p1Btn")
        self.horizontalLayout_14.addWidget(self.plotp2p1Btn)
        self.label_34 = QtWidgets.QLabel(self.iEAnalysisTab)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_14.addWidget(self.label_34)
        self.baselineCBox = QtWidgets.QComboBox(self.iEAnalysisTab)
        self.baselineCBox.setObjectName("baselineCBox")
        self.baselineCBox.addItem("")
        self.baselineCBox.addItem("")
        self.baselineCBox.addItem("")
        self.baselineCBox.addItem("")
        self.horizontalLayout_14.addWidget(self.baselineCBox)
        self.verticalLayout_12.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setContentsMargins(0, -1, -1, 0)
        self.horizontalLayout_33.setSpacing(1)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_41 = QtWidgets.QLabel(self.iEAnalysisTab)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_33.addWidget(self.label_41)
        self.startPotPeakdetLE = QtWidgets.QLineEdit(self.iEAnalysisTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startPotPeakdetLE.sizePolicy().hasHeightForWidth())
        self.startPotPeakdetLE.setSizePolicy(sizePolicy)
        self.startPotPeakdetLE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.startPotPeakdetLE.setMaxLength(10)
        self.startPotPeakdetLE.setObjectName("startPotPeakdetLE")
        self.horizontalLayout_33.addWidget(self.startPotPeakdetLE)
        self.label_40 = QtWidgets.QLabel(self.iEAnalysisTab)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_33.addWidget(self.label_40)
        self.endPotPeakdetLE = QtWidgets.QLineEdit(self.iEAnalysisTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endPotPeakdetLE.sizePolicy().hasHeightForWidth())
        self.endPotPeakdetLE.setSizePolicy(sizePolicy)
        self.endPotPeakdetLE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.endPotPeakdetLE.setMaxLength(10)
        self.endPotPeakdetLE.setObjectName("endPotPeakdetLE")
        self.horizontalLayout_33.addWidget(self.endPotPeakdetLE)
        self.label_11 = QtWidgets.QLabel(self.iEAnalysisTab)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_33.addWidget(self.label_11)
        self.startCatPotPeakLE = QtWidgets.QLineEdit(self.iEAnalysisTab)
        self.startCatPotPeakLE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.startCatPotPeakLE.setObjectName("startCatPotPeakLE")
        self.horizontalLayout_33.addWidget(self.startCatPotPeakLE)
        self.label_16 = QtWidgets.QLabel(self.iEAnalysisTab)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_33.addWidget(self.label_16)
        self.endCatPotPeakLE = QtWidgets.QLineEdit(self.iEAnalysisTab)
        self.endCatPotPeakLE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.endCatPotPeakLE.setObjectName("endCatPotPeakLE")
        self.horizontalLayout_33.addWidget(self.endCatPotPeakLE)
        self.halfQpChBox = QtWidgets.QCheckBox(self.iEAnalysisTab)
        self.halfQpChBox.setObjectName("halfQpChBox")
        self.horizontalLayout_33.addWidget(self.halfQpChBox)
        self.surfconcChBox = QtWidgets.QCheckBox(self.iEAnalysisTab)
        self.surfconcChBox.setObjectName("surfconcChBox")
        self.horizontalLayout_33.addWidget(self.surfconcChBox)
        self.verticalLayout_12.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_48 = QtWidgets.QLabel(self.iEAnalysisTab)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_39.addWidget(self.label_48)
        self.cycle2ratioSBox = QtWidgets.QSpinBox(self.iEAnalysisTab)
        self.cycle2ratioSBox.setMaximum(1500)
        self.cycle2ratioSBox.setProperty("value", 2)
        self.cycle2ratioSBox.setObjectName("cycle2ratioSBox")
        self.horizontalLayout_39.addWidget(self.cycle2ratioSBox)
        self.label_49 = QtWidgets.QLabel(self.iEAnalysisTab)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_39.addWidget(self.label_49)
        self.cycle1ratioSBox = QtWidgets.QSpinBox(self.iEAnalysisTab)
        self.cycle1ratioSBox.setMaximum(1500)
        self.cycle1ratioSBox.setProperty("value", 1)
        self.cycle1ratioSBox.setObjectName("cycle1ratioSBox")
        self.horizontalLayout_39.addWidget(self.cycle1ratioSBox)
        self.label_50 = QtWidgets.QLabel(self.iEAnalysisTab)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_39.addWidget(self.label_50)
        self.iterationsSBox = QtWidgets.QSpinBox(self.iEAnalysisTab)
        self.iterationsSBox.setProperty("value", 1)
        self.iterationsSBox.setObjectName("iterationsSBox")
        self.horizontalLayout_39.addWidget(self.iterationsSBox)
        self.verticalLayout_12.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.ploti2i1Btn = QtWidgets.QPushButton(self.iEAnalysisTab)
        self.ploti2i1Btn.setObjectName("ploti2i1Btn")
        self.horizontalLayout_17.addWidget(self.ploti2i1Btn)
        self.plotAEpBtn = QtWidgets.QPushButton(self.iEAnalysisTab)
        self.plotAEpBtn.setObjectName("plotAEpBtn")
        self.horizontalLayout_17.addWidget(self.plotAEpBtn)
        self.pushButton_10 = QtWidgets.QPushButton(self.iEAnalysisTab)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_17.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.iEAnalysisTab)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_17.addWidget(self.pushButton_11)
        self.verticalLayout_12.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_36.addLayout(self.verticalLayout_12)
        self.tabWidget_3.addTab(self.iEAnalysisTab, "")
        self.itAnalysisTab = QtWidgets.QWidget()
        self.itAnalysisTab.setObjectName("itAnalysisTab")
        self.plotQanodicBtn = QtWidgets.QPushButton(self.itAnalysisTab)
        self.plotQanodicBtn.setGeometry(QtCore.QRect(40, 30, 113, 32))
        self.plotQanodicBtn.setObjectName("plotQanodicBtn")
        self.plotQcathodicBtn = QtWidgets.QPushButton(self.itAnalysisTab)
        self.plotQcathodicBtn.setGeometry(QtCore.QRect(180, 30, 113, 32))
        self.plotQcathodicBtn.setObjectName("plotQcathodicBtn")
        self.tabWidget_3.addTab(self.itAnalysisTab, "")
        self.EtAnalysisTab = QtWidgets.QWidget()
        self.EtAnalysisTab.setObjectName("EtAnalysisTab")
        self.tabWidget_3.addTab(self.EtAnalysisTab, "")
        self.horizontalLayout_10.addWidget(self.tabWidget_3)
        self.line_3 = QtWidgets.QFrame(self.plotmapsTab)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_10.addWidget(self.line_3)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSpacing(1)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_17 = QtWidgets.QLabel(self.plotmapsTab)
        self.label_17.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_13.addWidget(self.label_17)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pointingRBtn = QtWidgets.QRadioButton(self.plotmapsTab)
        self.pointingRBtn.setChecked(True)
        self.pointingRBtn.setObjectName("pointingRBtn")
        self.buttonGroup_3 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_3.setObjectName("buttonGroup_3")
        self.buttonGroup_3.addButton(self.pointingRBtn)
        self.horizontalLayout_12.addWidget(self.pointingRBtn)
        self.markingRBtn = QtWidgets.QRadioButton(self.plotmapsTab)
        self.markingRBtn.setObjectName("markingRBtn")
        self.buttonGroup_3.addButton(self.markingRBtn)
        self.horizontalLayout_12.addWidget(self.markingRBtn)
        self.clearMarksBtn = QtWidgets.QRadioButton(self.plotmapsTab)
        self.clearMarksBtn.setCheckable(True)
        self.clearMarksBtn.setObjectName("clearMarksBtn")
        self.buttonGroup_3.addButton(self.clearMarksBtn)
        self.horizontalLayout_12.addWidget(self.clearMarksBtn)
        self.verticalLayout_13.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.exportAllChBox = QtWidgets.QCheckBox(self.plotmapsTab)
        self.exportAllChBox.setObjectName("exportAllChBox")
        self.horizontalLayout_13.addWidget(self.exportAllChBox)
        self.plotHopMapBtn = QtWidgets.QPushButton(self.plotmapsTab)
        self.plotHopMapBtn.setObjectName("plotHopMapBtn")
        self.horizontalLayout_13.addWidget(self.plotHopMapBtn)
        self.verticalLayout_13.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setSpacing(2)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_51 = QtWidgets.QLabel(self.plotmapsTab)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_38.addWidget(self.label_51)
        self.minCurrentLE = QtWidgets.QLineEdit(self.plotmapsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minCurrentLE.sizePolicy().hasHeightForWidth())
        self.minCurrentLE.setSizePolicy(sizePolicy)
        self.minCurrentLE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.minCurrentLE.setObjectName("minCurrentLE")
        self.horizontalLayout_38.addWidget(self.minCurrentLE)
        self.label_52 = QtWidgets.QLabel(self.plotmapsTab)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_38.addWidget(self.label_52)
        self.maxCurrentLE = QtWidgets.QLineEdit(self.plotmapsTab)
        self.maxCurrentLE.setMinimumSize(QtCore.QSize(0, 20))
        self.maxCurrentLE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.maxCurrentLE.setObjectName("maxCurrentLE")
        self.horizontalLayout_38.addWidget(self.maxCurrentLE)
        self.verticalLayout_13.addLayout(self.horizontalLayout_38)
        self.detectNoisyBtn = QtWidgets.QPushButton(self.plotmapsTab)
        self.detectNoisyBtn.setObjectName("detectNoisyBtn")
        self.verticalLayout_13.addWidget(self.detectNoisyBtn)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem7)
        self.horizontalLayout_10.addLayout(self.verticalLayout_13)
        self.line_4 = QtWidgets.QFrame(self.plotmapsTab)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_10.addWidget(self.line_4)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_18 = QtWidgets.QLabel(self.plotmapsTab)
        self.label_18.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_14.addWidget(self.label_18)
        self.horizontalLayout_10.addLayout(self.verticalLayout_14)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem9)
        self.tabWidget.addTab(self.plotmapsTab, "")
        self.plotdataTab = QtWidgets.QWidget()
        self.plotdataTab.setObjectName("plotdataTab")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.plotdataTab)
        self.verticalLayout_30.setContentsMargins(12, 2, 12, 2)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_22 = QtWidgets.QLabel(self.plotdataTab)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_23.addWidget(self.label_22)
        self.iEdataCBox = QtWidgets.QCheckBox(self.plotdataTab)
        self.iEdataCBox.setChecked(True)
        self.iEdataCBox.setObjectName("iEdataCBox")
        self.verticalLayout_23.addWidget(self.iEdataCBox)
        self.itdataChBox = QtWidgets.QCheckBox(self.plotdataTab)
        self.itdataChBox.setObjectName("itdataChBox")
        self.verticalLayout_23.addWidget(self.itdataChBox)
        self.EtdataChBox = QtWidgets.QCheckBox(self.plotdataTab)
        self.EtdataChBox.setObjectName("EtdataChBox")
        self.verticalLayout_23.addWidget(self.EtdataChBox)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem10)
        self.horizontalLayout_20.addLayout(self.verticalLayout_23)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_24.setSpacing(1)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setSpacing(1)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.selectAllBtn = QtWidgets.QPushButton(self.plotdataTab)
        self.selectAllBtn.setObjectName("selectAllBtn")
        self.horizontalLayout_23.addWidget(self.selectAllBtn)
        self.clearSelectedBtn = QtWidgets.QPushButton(self.plotdataTab)
        self.clearSelectedBtn.setObjectName("clearSelectedBtn")
        self.horizontalLayout_23.addWidget(self.clearSelectedBtn)
        self.line_8 = QtWidgets.QFrame(self.plotdataTab)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_23.addWidget(self.line_8)
        self.selectCyclesBtn = QtWidgets.QPushButton(self.plotdataTab)
        self.selectCyclesBtn.setObjectName("selectCyclesBtn")
        self.horizontalLayout_23.addWidget(self.selectCyclesBtn)
        self.selectCyclesSpin = QtWidgets.QSpinBox(self.plotdataTab)
        self.selectCyclesSpin.setMinimum(1)
        self.selectCyclesSpin.setMaximum(300)
        self.selectCyclesSpin.setObjectName("selectCyclesSpin")
        self.horizontalLayout_23.addWidget(self.selectCyclesSpin)
        self.verticalLayout_24.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_18.setSpacing(1)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_24.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_19.setSpacing(1)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.selectRangeBtn = QtWidgets.QPushButton(self.plotdataTab)
        self.selectRangeBtn.setObjectName("selectRangeBtn")
        self.horizontalLayout_19.addWidget(self.selectRangeBtn)
        self.selectRangeLE = QtWidgets.QLineEdit(self.plotdataTab)
        self.selectRangeLE.setMaximumSize(QtCore.QSize(100, 16777215))
        self.selectRangeLE.setMaxLength(20)
        self.selectRangeLE.setClearButtonEnabled(True)
        self.selectRangeLE.setObjectName("selectRangeLE")
        self.horizontalLayout_19.addWidget(self.selectRangeLE)
        self.label_21 = QtWidgets.QLabel(self.plotdataTab)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_19.addWidget(self.label_21)
        self.selectRangeCycleSpin = QtWidgets.QSpinBox(self.plotdataTab)
        self.selectRangeCycleSpin.setObjectName("selectRangeCycleSpin")
        self.horizontalLayout_19.addWidget(self.selectRangeCycleSpin)
        self.verticalLayout_24.addLayout(self.horizontalLayout_19)
        self.dataListWidget = QtWidgets.QListWidget(self.plotdataTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataListWidget.sizePolicy().hasHeightForWidth())
        self.dataListWidget.setSizePolicy(sizePolicy)
        self.dataListWidget.setObjectName("dataListWidget")
        self.verticalLayout_24.addWidget(self.dataListWidget)
        self.plotECdataButton = QtWidgets.QPushButton(self.plotdataTab)
        self.plotECdataButton.setObjectName("plotECdataButton")
        self.verticalLayout_24.addWidget(self.plotECdataButton)
        self.saveECdataButton = QtWidgets.QPushButton(self.plotdataTab)
        self.saveECdataButton.setObjectName("saveECdataButton")
        self.verticalLayout_24.addWidget(self.saveECdataButton)
        self.horizontalLayout_20.addLayout(self.verticalLayout_24)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.smoothECdataChBox = QtWidgets.QCheckBox(self.plotdataTab)
        self.smoothECdataChBox.setObjectName("smoothECdataChBox")
        self.horizontalLayout_21.addWidget(self.smoothECdataChBox)
        self.smoothECdataSBox = QtWidgets.QSpinBox(self.plotdataTab)
        self.smoothECdataSBox.setMinimum(3)
        self.smoothECdataSBox.setMaximum(900)
        self.smoothECdataSBox.setSingleStep(2)
        self.smoothECdataSBox.setObjectName("smoothECdataSBox")
        self.horizontalLayout_21.addWidget(self.smoothECdataSBox)
        self.verticalLayout_28.addLayout(self.horizontalLayout_21)
        self.averagedataChBox = QtWidgets.QCheckBox(self.plotdataTab)
        self.averagedataChBox.setObjectName("averagedataChBox")
        self.verticalLayout_28.addWidget(self.averagedataChBox)
        self.normalizeECdataAreaChBox = QtWidgets.QCheckBox(self.plotdataTab)
        self.normalizeECdataAreaChBox.setObjectName("normalizeECdataAreaChBox")
        self.verticalLayout_28.addWidget(self.normalizeECdataAreaChBox)
        self.showECdataLegendChBox = QtWidgets.QCheckBox(self.plotdataTab)
        self.showECdataLegendChBox.setChecked(True)
        self.showECdataLegendChBox.setObjectName("showECdataLegendChBox")
        self.verticalLayout_28.addWidget(self.showECdataLegendChBox)
        self.analysisECBtn = QtWidgets.QPushButton(self.plotdataTab)
        self.analysisECBtn.setObjectName("analysisECBtn")
        self.verticalLayout_28.addWidget(self.analysisECBtn)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_28.addItem(spacerItem11)
        self.horizontalLayout_20.addLayout(self.verticalLayout_28)
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_35 = QtWidgets.QLabel(self.plotdataTab)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_5.addWidget(self.label_35)
        self.ElabelLE = QtWidgets.QLineEdit(self.plotdataTab)
        self.ElabelLE.setObjectName("ElabelLE")
        self.horizontalLayout_5.addWidget(self.ElabelLE)
        self.verticalLayout_34.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_37 = QtWidgets.QLabel(self.plotdataTab)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_7.addWidget(self.label_37)
        self.ilabelLE = QtWidgets.QLineEdit(self.plotdataTab)
        self.ilabelLE.setObjectName("ilabelLE")
        self.horizontalLayout_7.addWidget(self.ilabelLE)
        self.verticalLayout_34.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_39 = QtWidgets.QLabel(self.plotdataTab)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_16.addWidget(self.label_39)
        self.tlabelLE = QtWidgets.QLineEdit(self.plotdataTab)
        self.tlabelLE.setObjectName("tlabelLE")
        self.horizontalLayout_16.addWidget(self.tlabelLE)
        self.verticalLayout_34.addLayout(self.horizontalLayout_16)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_34.addItem(spacerItem12)
        self.line = QtWidgets.QFrame(self.plotdataTab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_34.addWidget(self.line)
        self.horizontalLayout_20.addLayout(self.verticalLayout_34)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem13)
        self.verticalLayout_29.addLayout(self.horizontalLayout_20)
        self.verticalLayout_30.addLayout(self.verticalLayout_29)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_30.addItem(spacerItem14)
        self.tabWidget.addTab(self.plotdataTab, "")
        self.settingsTab = QtWidgets.QWidget()
        self.settingsTab.setObjectName("settingsTab")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.settingsTab)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.convertEChBox = QtWidgets.QCheckBox(self.settingsTab)
        self.convertEChBox.setObjectName("convertEChBox")
        self.horizontalLayout_31.addWidget(self.convertEChBox)
        self.convertEshiftLE = QtWidgets.QLineEdit(self.settingsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.convertEshiftLE.sizePolicy().hasHeightForWidth())
        self.convertEshiftLE.setSizePolicy(sizePolicy)
        self.convertEshiftLE.setObjectName("convertEshiftLE")
        self.horizontalLayout_31.addWidget(self.convertEshiftLE)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem15)
        self.verticalLayout_38.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_42 = QtWidgets.QLabel(self.settingsTab)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_34.addWidget(self.label_42)
        self.tipdiamLE = QtWidgets.QLineEdit(self.settingsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tipdiamLE.sizePolicy().hasHeightForWidth())
        self.tipdiamLE.setSizePolicy(sizePolicy)
        self.tipdiamLE.setObjectName("tipdiamLE")
        self.horizontalLayout_34.addWidget(self.tipdiamLE)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem16)
        self.verticalLayout_38.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_43 = QtWidgets.QLabel(self.settingsTab)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_35.addWidget(self.label_43)
        self.nelLE = QtWidgets.QLineEdit(self.settingsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nelLE.sizePolicy().hasHeightForWidth())
        self.nelLE.setSizePolicy(sizePolicy)
        self.nelLE.setObjectName("nelLE")
        self.horizontalLayout_35.addWidget(self.nelLE)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem17)
        self.verticalLayout_38.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_22.addLayout(self.verticalLayout_38)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_36 = QtWidgets.QLabel(self.settingsTab)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_30.addWidget(self.label_36)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_38 = QtWidgets.QLabel(self.settingsTab)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_27.addWidget(self.label_38)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_27)
        self.tabWidget.addTab(self.settingsTab, "")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget_2.setMinimumSize(QtCore.QSize(0, 350))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.topoTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topoTab.sizePolicy().hasHeightForWidth())
        self.topoTab.setSizePolicy(sizePolicy)
        self.topoTab.setObjectName("topoTab")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.topoTab)
        self.verticalLayout_32.setContentsMargins(5, 2, 5, 2)
        self.verticalLayout_32.setSpacing(2)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.splitter_3 = QtWidgets.QSplitter(self.topoTab)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.topoFrame1 = QtWidgets.QFrame(self.splitter_3)
        self.topoFrame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topoFrame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topoFrame1.setObjectName("topoFrame1")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.topoFrame1)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tab1vBox1 = QtWidgets.QVBoxLayout()
        self.tab1vBox1.setObjectName("tab1vBox1")
        self.verticalLayout_9.addLayout(self.tab1vBox1)
        self.topoFrame2 = QtWidgets.QFrame(self.splitter_3)
        self.topoFrame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topoFrame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topoFrame2.setObjectName("topoFrame2")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.topoFrame2)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(2)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.tab1vBox2 = QtWidgets.QVBoxLayout()
        self.tab1vBox2.setObjectName("tab1vBox2")
        self.verticalLayout_15.addLayout(self.tab1vBox2)
        self.topoFrame3 = QtWidgets.QFrame(self.splitter_3)
        self.topoFrame3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topoFrame3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topoFrame3.setObjectName("topoFrame3")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.topoFrame3)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(2)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.tab1vBox3 = QtWidgets.QVBoxLayout()
        self.tab1vBox3.setObjectName("tab1vBox3")
        self.verticalLayout_22.addLayout(self.tab1vBox3)
        self.verticalLayout_32.addWidget(self.splitter_3)
        self.tabWidget_2.addTab(self.topoTab, "")
        self.ecmoviesTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ecmoviesTab.sizePolicy().hasHeightForWidth())
        self.ecmoviesTab.setSizePolicy(sizePolicy)
        self.ecmoviesTab.setObjectName("ecmoviesTab")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.ecmoviesTab)
        self.verticalLayout_35.setContentsMargins(5, 2, 5, 2)
        self.verticalLayout_35.setSpacing(2)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.splitter_4 = QtWidgets.QSplitter(self.ecmoviesTab)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.ecmoviesFrame1 = QtWidgets.QFrame(self.splitter_4)
        self.ecmoviesFrame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ecmoviesFrame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ecmoviesFrame1.setObjectName("ecmoviesFrame1")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.ecmoviesFrame1)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(2)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.ecmoviesLayout1 = QtWidgets.QVBoxLayout()
        self.ecmoviesLayout1.setObjectName("ecmoviesLayout1")
        self.verticalLayout_16.addLayout(self.ecmoviesLayout1)
        self.ecmoviesFrame2 = QtWidgets.QFrame(self.splitter_4)
        self.ecmoviesFrame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ecmoviesFrame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ecmoviesFrame2.setObjectName("ecmoviesFrame2")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.ecmoviesFrame2)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(2)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.ecmoviesLayout2 = QtWidgets.QVBoxLayout()
        self.ecmoviesLayout2.setObjectName("ecmoviesLayout2")
        self.verticalLayout_18.addLayout(self.ecmoviesLayout2)
        self.ecmoviesFrame3 = QtWidgets.QFrame(self.splitter_4)
        self.ecmoviesFrame3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ecmoviesFrame3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ecmoviesFrame3.setObjectName("ecmoviesFrame3")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.ecmoviesFrame3)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(2)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.ecmoviesLayout3 = QtWidgets.QVBoxLayout()
        self.ecmoviesLayout3.setObjectName("ecmoviesLayout3")
        self.verticalLayout_20.addLayout(self.ecmoviesLayout3)
        self.verticalLayout_35.addWidget(self.splitter_4)
        self.tabWidget_2.addTab(self.ecmoviesTab, "")
        self.ecmapsTab = QtWidgets.QWidget()
        self.ecmapsTab.setObjectName("ecmapsTab")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.ecmapsTab)
        self.verticalLayout_37.setContentsMargins(5, 2, 5, 2)
        self.verticalLayout_37.setSpacing(2)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.splitter_5 = QtWidgets.QSplitter(self.ecmapsTab)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.frame_5 = QtWidgets.QFrame(self.splitter_5)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(2)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.ecmapsLayout1 = QtWidgets.QVBoxLayout()
        self.ecmapsLayout1.setObjectName("ecmapsLayout1")
        self.verticalLayout_21.addLayout(self.ecmapsLayout1)
        self.frame_6 = QtWidgets.QFrame(self.splitter_5)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_33.setSpacing(2)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.ecmapsLayout2 = QtWidgets.QVBoxLayout()
        self.ecmapsLayout2.setObjectName("ecmapsLayout2")
        self.verticalLayout_33.addLayout(self.ecmapsLayout2)
        self.frame_7 = QtWidgets.QFrame(self.splitter_5)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_36.setSpacing(2)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.ecmapsLayout3 = QtWidgets.QVBoxLayout()
        self.ecmapsLayout3.setObjectName("ecmapsLayout3")
        self.verticalLayout_36.addLayout(self.ecmapsLayout3)
        self.verticalLayout_37.addWidget(self.splitter_5)
        self.tabWidget_2.addTab(self.ecmapsTab, "")
        self.ecdataTab = QtWidgets.QWidget()
        self.ecdataTab.setObjectName("ecdataTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.ecdataTab)
        self.verticalLayout_3.setContentsMargins(5, 2, 5, 2)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter_2 = QtWidgets.QSplitter(self.ecdataTab)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.frame = QtWidgets.QFrame(self.splitter_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(2)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.ecdataLayout1 = QtWidgets.QVBoxLayout()
        self.ecdataLayout1.setObjectName("ecdataLayout1")
        self.verticalLayout_25.addLayout(self.ecdataLayout1)
        self.frame_3 = QtWidgets.QFrame(self.splitter_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setSpacing(2)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.ecdataLayout2 = QtWidgets.QVBoxLayout()
        self.ecdataLayout2.setObjectName("ecdataLayout2")
        self.verticalLayout_26.addLayout(self.ecdataLayout2)
        self.frame_2 = QtWidgets.QFrame(self.splitter_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setSpacing(2)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.ecdataLayout3 = QtWidgets.QVBoxLayout()
        self.ecdataLayout3.setObjectName("ecdataLayout3")
        self.verticalLayout_27.addLayout(self.ecdataLayout3)
        self.verticalLayout_3.addWidget(self.splitter_2)
        self.tabWidget_2.addTab(self.ecdataTab, "")
        self.verticalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1228, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout_WEC_AL = QtWidgets.QAction(MainWindow)
        self.actionAbout_WEC_AL.setObjectName("actionAbout_WEC_AL")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionLog = QtWidgets.QAction(MainWindow)
        self.actionLog.setObjectName("actionLog")
        self.menuFile.addAction(self.actionQuit)
        self.menuAbout.addAction(self.actionAbout_WEC_AL)
        self.menuHelp.addAction(self.actionLog)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.selectFileButton.setText(_translate("MainWindow", "Select file"))
        self.clearcacheBtn.setText(_translate("MainWindow", "Clear cached data"))
        self.weigLogo.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/resources/logo.png\" /></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">X width</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Y width</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Hopping distance</span></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Acqusition rate (µs)</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Num channels</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Cycles</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">LabVIEW program</span></p></body></html>"))
        self.labviewprogramCBox.setItemText(1, _translate("MainWindow", "Scan_Hopping CV at Surface.vi"))
        self.labviewprogramCBox.setItemText(2, _translate("MainWindow", "Scan_Hopping with IT at Surface.vi"))
        self.labviewprogramCBox.setItemText(3, _translate("MainWindow", "Scan_Hopping Multiple CVs at Surface.vi"))
        self.labviewprogramCBox.setItemText(4, _translate("MainWindow", "Approach then CV.vi"))
        self.labviewprogramCBox.setItemText(5, _translate("MainWindow", "Scan_Hopping Multiple LSVs at Surface.vi"))
        self.labviewprogramCBox.setItemText(6, _translate("MainWindow", "Scan_Hopping Different Pause at Surface Durations.vi"))
        self.labviewprogramCBox.setItemText(7, _translate("MainWindow", "Approach then IT.vi"))
        self.labviewprogramCBox.setItemText(8, _translate("MainWindow", "Scan_Hopping with IT at Surface.vi"))
        self.labviewprogramCBox.setItemText(9, _translate("MainWindow", "Scan_Hopping Multiple CVs at Surface_onedir.vi"))
        self.labviewprogramCBox.setItemText(10, _translate("MainWindow", "Scan_Hopping_Daniel_special.vi"))
        self.labviewprogramCBox.setItemText(11, _translate("MainWindow", "Scan_Hopping with Galvanostatic measure_single_one_dir.vi"))
        self.labviewprogramCBox.setItemText(12, _translate("MainWindow", "Scan_Hopping_multiple_CVs-LSVs_at_Surface.vi"))
        self.labviewprogramCBox.setItemText(13, _translate("MainWindow", "Scan_Hopping with Galvanostatic measure_double_one_dir.vi"))
        self.labviewprogramCBox.setItemText(14, _translate("MainWindow", "Watch_Current.vi"))
        self.labviewprogramCBox.setItemText(15, _translate("MainWindow", "Scan_Hopping.vi"))
        self.plotAllDataBtn.setText(_translate("MainWindow", "Plot raw data"))
        self.xchannelCBox.setText(_translate("MainWindow", "X"))
        self.ychannelCBox.setText(_translate("MainWindow", "Y"))
        self.zchannelCBox.setText(_translate("MainWindow", "Z"))
        self.lnchannelCBox.setText(_translate("MainWindow", "LN"))
        self.c1channelCBox.setText(_translate("MainWindow", "C1"))
        self.v1channelCBox.setText(_translate("MainWindow", "V1"))
        self.c2channelCBox.setText(_translate("MainWindow", "C2"))
        self.v2channelCBox.setText(_translate("MainWindow", "V2"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#0000ff;\">Local Settings</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#0000ff;\">Global Settings</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#0000ff;\">Saved channels</span></p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#0000ff;\">Channel numbers</span></p></body></html>"))
        self.label_30.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">V1</span></p></body></html>"))
        self.label_44.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">C2</span></p></body></html>"))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Z</span></p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Y</span></p></body></html>"))
        self.label_45.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">V2</span></p></body></html>"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">X</span></p></body></html>"))
        self.label_29.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">LN</span></p></body></html>"))
        self.label_31.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">C1</span></p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">dt</span></p></body></html>"))
        self.setCNBtn.setText(_translate("MainWindow", "Sets of CN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Data Info"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Topography</span></p></body></html>"))
        self.plotTopoBtn.setText(_translate("MainWindow", "Plot Topo"))
        self.flattenTopoChBox.setText(_translate("MainWindow", "Flattened"))
        self.topo3DChBox.setText(_translate("MainWindow", "3D"))
        self.normalizeTopoChBox.setText(_translate("MainWindow", "Normalize Topo"))
        self.checkBox_10.setText(_translate("MainWindow", "Raw lateral"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">General</span></p></body></html>"))
        self.replaceNaNsChBox.setText(_translate("MainWindow", "Replace NaNs"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#0000ff;\">Max value threshold</span></p></body></html>"))
        self.nanthresholdLE.setText(_translate("MainWindow", "8e-12"))
        self.plotCurrentDensityChBox.setText(_translate("MainWindow", "Plot current density"))
        self.smoothDataMapChBox.setText(_translate("MainWindow", "Smooth data"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">EC Movies</span></p></body></html>"))
        self.iEmovieChBox.setText(_translate("MainWindow", "C1/V1"))
        self.itmovieChBox.setText(_translate("MainWindow", "C1/t"))
        self.EtmovieChBox.setText(_translate("MainWindow", "V1/t"))
        self.label_14.setText(_translate("MainWindow", "Cycle:"))
        self.cmapMovieCbox.setItemText(0, _translate("MainWindow", "jet"))
        self.cmapMovieCbox.setItemText(1, _translate("MainWindow", "jet_r"))
        self.plotMoviesBtn.setText(_translate("MainWindow", "Plot movies"))
        self.stopMovieBtn.setText(_translate("MainWindow", "Stop"))
        self.plotSingleFrameBtn.setText(_translate("MainWindow", "Plot Frame"))
        self.frameNumRBtn.setText(_translate("MainWindow", "Frame #"))
        self.frameXvalueRBtn.setText(_translate("MainWindow", "Xvalue"))
        self.showFrameListBtn.setText(_translate("MainWindow", "Framelist"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0000ff;\">Formatting:</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "Speed (ms)"))
        self.skipframesChBox.setText(_translate("MainWindow", "Skip frames"))
        self.saveMovieChBox.setText(_translate("MainWindow", "Save movie"))
        self.movieNoGUIChBox.setText(_translate("MainWindow", "No GUI"))
        self.label_47.setText(_translate("MainWindow", "Limits:"))
        self.autoLimitsRBtn.setText(_translate("MainWindow", "Auto"))
        self.dynamicLimitsRBtn.setText(_translate("MainWindow", "Dynamic"))
        self.manualLimitsRBtn.setText(_translate("MainWindow", "Manual"))
        self.label_32.setText(_translate("MainWindow", "min"))
        self.label_33.setText(_translate("MainWindow", "max"))
        self.plotSinglePeakMapsBtn.setText(_translate("MainWindow", "Plot singlePeak"))
        self.plotp2p1Btn.setText(_translate("MainWindow", "p2 / p1"))
        self.label_34.setText(_translate("MainWindow", "Baseline"))
        self.baselineCBox.setItemText(0, _translate("MainWindow", "ZhangFit"))
        self.baselineCBox.setItemText(1, _translate("MainWindow", "Peakutils"))
        self.baselineCBox.setItemText(2, _translate("MainWindow", "ModPoly"))
        self.baselineCBox.setItemText(3, _translate("MainWindow", "IModPoly"))
        self.label_41.setText(_translate("MainWindow", "<html><head/><body><p>E<span style=\" font-size:10pt;\">(fw)</span><span style=\" vertical-align:sub;\">start</span></p></body></html>"))
        self.startPotPeakdetLE.setText(_translate("MainWindow", "0.0"))
        self.label_40.setText(_translate("MainWindow", "<html><head/><body><p>E<span style=\" font-size:10pt;\">(fw)</span><span style=\" vertical-align:sub;\">end</span></p></body></html>"))
        self.endPotPeakdetLE.setText(_translate("MainWindow", "0.0"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p>E<span style=\" font-size:10pt;\">(bw)</span><span style=\" vertical-align:sub;\">start</span></p></body></html>"))
        self.startCatPotPeakLE.setText(_translate("MainWindow", "0.0"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p>E<span style=\" font-size:10pt;\">(bw)</span><span style=\" vertical-align:sub;\">end</span></p></body></html>"))
        self.endCatPotPeakLE.setText(_translate("MainWindow", "0.0"))
        self.halfQpChBox.setText(_translate("MainWindow", "HalfQp"))
        self.surfconcChBox.setText(_translate("MainWindow", "Γads"))
        self.label_48.setText(_translate("MainWindow", "cycle2"))
        self.label_49.setText(_translate("MainWindow", "cycle1"))
        self.label_50.setText(_translate("MainWindow", "Iterations"))
        self.ploti2i1Btn.setText(_translate("MainWindow", "i2/i1"))
        self.plotAEpBtn.setText(_translate("MainWindow", "Plot ΔEp"))
        self.pushButton_10.setText(_translate("MainWindow", "ipa/ipc"))
        self.pushButton_11.setText(_translate("MainWindow", "Qpa/Qpc"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.iEAnalysisTab), _translate("MainWindow", "iE Analysis"))
        self.plotQanodicBtn.setText(_translate("MainWindow", "Qanodic"))
        self.plotQcathodicBtn.setText(_translate("MainWindow", "Qcathodic"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.itAnalysisTab), _translate("MainWindow", "it Analysis"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.EtAnalysisTab), _translate("MainWindow", "Et Analysis"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#800080;\">Map marking</span></p></body></html>"))
        self.pointingRBtn.setText(_translate("MainWindow", "Pointing"))
        self.markingRBtn.setText(_translate("MainWindow", "Marking"))
        self.clearMarksBtn.setText(_translate("MainWindow", "Clear marks"))
        self.exportAllChBox.setText(_translate("MainWindow", "Export all"))
        self.plotHopMapBtn.setText(_translate("MainWindow", "Plot hop map"))
        self.label_51.setText(_translate("MainWindow", "Min"))
        self.minCurrentLE.setText(_translate("MainWindow", "1e-11"))
        self.label_52.setText(_translate("MainWindow", "Max"))
        self.maxCurrentLE.setText(_translate("MainWindow", "4e-9"))
        self.detectNoisyBtn.setText(_translate("MainWindow", "Remove min/max and noisy"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#800080;\">Placeholder</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.plotmapsTab), _translate("MainWindow", "Plot Maps"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Data to plot</span></p></body></html>"))
        self.iEdataCBox.setText(_translate("MainWindow", "C1 vs V1"))
        self.itdataChBox.setText(_translate("MainWindow", "C1 vs t"))
        self.EtdataChBox.setText(_translate("MainWindow", "V1 vs t"))
        self.selectAllBtn.setText(_translate("MainWindow", "Select all"))
        self.clearSelectedBtn.setText(_translate("MainWindow", "Clear selected"))
        self.selectCyclesBtn.setText(_translate("MainWindow", "Select  cycle"))
        self.selectRangeBtn.setText(_translate("MainWindow", "Select range"))
        self.label_21.setText(_translate("MainWindow", "Cycle"))
        self.plotECdataButton.setText(_translate("MainWindow", "Plot EC data"))
        self.saveECdataButton.setText(_translate("MainWindow", "Save figures to disk"))
        self.smoothECdataChBox.setText(_translate("MainWindow", "Smooth data"))
        self.averagedataChBox.setText(_translate("MainWindow", "Average data"))
        self.normalizeECdataAreaChBox.setText(_translate("MainWindow", "Normalize by area\n"
"(plot current density)"))
        self.showECdataLegendChBox.setText(_translate("MainWindow", "Show legend"))
        self.analysisECBtn.setText(_translate("MainWindow", "Analysis EC data"))
        self.label_35.setText(_translate("MainWindow", "E label"))
        self.label_37.setText(_translate("MainWindow", "i label"))
        self.label_39.setText(_translate("MainWindow", "t label"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.plotdataTab), _translate("MainWindow", "Plot Data"))
        self.convertEChBox.setText(_translate("MainWindow", "Convert potentials (V)"))
        self.label_42.setText(_translate("MainWindow", "tip diameter (µm)"))
        self.label_43.setText(_translate("MainWindow", "<html><head/><body><p>n e<span style=\" vertical-align:super;\">-</span></p></body></html>"))
        self.label_36.setText(_translate("MainWindow", "Font sizes, etc."))
        self.label_38.setText(_translate("MainWindow", "Other formatting stuff"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingsTab), _translate("MainWindow", "Settings"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.topoTab), _translate("MainWindow", "Topography"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.ecmoviesTab), _translate("MainWindow", "EC Movies"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.ecmapsTab), _translate("MainWindow", "EC Maps"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.ecdataTab), _translate("MainWindow", "EC Plots"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout_WEC_AL.setText(_translate("MainWindow", "About WEC-AL"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionLog.setText(_translate("MainWindow", "Log"))

from tips.ui import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

